import type { Metadata } from "next";
import "./globals.css";
import { WalletProviders } from "./providers/wallets.providers";
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body >
        <WalletProviders>
          { props.children }
        </WalletProviders>
      </body>
    </html>
  );
}
